# Generated by Django 5.0.6 on 2025-01-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="genre",
        ),
        migrations.AddField(
            model_name="movies",
            name="genre",
            field=models.ManyToManyField(to="master_data.genre"),
        ),
    ]
